# Generated by Django 4.2.23 on 2025-07-31 16:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Atividade",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("titulo", models.CharField(max_length=200, verbose_name="Título")),
                ("descricao", models.TextField(blank=True, verbose_name="Descrição")),
                (
                    "prioridade",
                    models.CharField(
                        choices=[
                            ("alta", "Alta"),
                            ("media", "Média"),
                            ("baixa", "Baixa"),
                        ],
                        default="media",
                        max_length=10,
                        verbose_name="Prioridade",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("a_fazer", "A Fazer"),
                            ("em_progresso", "Em Progresso"),
                            ("em_revisao", "Em Revisão"),
                            ("concluido", "Concluído"),
                        ],
                        default="a_fazer",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "data_vencimento",
                    models.DateField(
                        blank=True, null=True, verbose_name="Data de Vencimento"
                    ),
                ),
                ("criado_em", models.DateTimeField(auto_now_add=True)),
                ("atualizado_em", models.DateTimeField(auto_now=True)),
                (
                    "responsavel",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Responsável",
                    ),
                ),
            ],
            options={
                "ordering": ["-prioridade", "data_vencimento"],
            },
        ),
    ]
