# Generated by Django 4.2.23 on 2025-07-31 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atividades", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="atividade",
            name="prioridade",
            field=models.CharField(
                choices=[
                    ("alta prioridade", "Alta Prioridade"),
                    ("media prioridade", "Média Prioridade"),
                    ("baixa prioridade", "Baixa Prioridade"),
                ],
                default="media prioridade",
                max_length=20,
                verbose_name="Prioridade",
            ),
        ),
    ]
