# Generated by Django 4.2.23 on 2025-08-08 12:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("atividades", "0002_alter_atividade_prioridade"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="atividade",
            name="atualizado_em",
        ),
        migrations.AddField(
            model_name="atividade",
            name="atualizado_por",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="atividades_atualizadas",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
