# Generated by Django 4.2.23 on 2025-08-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("atividades", "0003_remove_atividade_atualizado_em_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="atividade",
            name="atualizado_em",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
